config/routes.rb
MusicApp::Application.routes.draw do

  get    'bands',            to: 'bands#index',      as: 'root'
  get    'sessions/new',     to: 'sessions#new',     as: 'login_page'
  post   'sessions/create',  to: 'sessions#create',  as: 'login'
  delete 'sessions/destroy', to: 'sessions#destroy', as: 'logout'
  resources :users, only: [:index, :new, :create, :show]
  resources :bands
  resources :albums
  resources :tracks
  resources :notes

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :album_name, :band_id

  belongs_to :band
  has_many   :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :band_name

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :text, :track_id, :user_id

  belongs_to :track
  belongs_to :user

  has_one :album, through: :track
  has_one :band,  through: :album
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :track_name, :album_id

  belongs_to :album
  has_one    :band, through: :album
  has_many   :notes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password
  attr_reader :password

  before_validation :ensure_session_token
  has_many :notes, dependent: :destroy

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)
    return nil unless @user
    BCrypt::Password.new(@user.pass_digest).is_password?(password) ? @user : nil
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.pass_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album  = Album.find(params[:id])
    @band   = @album.band
    @tracks = @album.tracks
  end

  def create
    @album = Album.new(params[:album])

    flash[:notice] = (@album.save) ? "Album added" : "Failure"
    redirect_to :back
  end

  def destroy
    @album = Album.find(params[:id])
    @band  = @album.band

    flash[:notice] = (@album.destroy) ? "Album removed" : "Failure"
    redirect_to band_url(@band.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands  = Band.all
  end

  def show
    @band   = Band.find(params[:id])
    @albums = @band.albums
  end

  def create
    @band = Band.new(params[:band])

    flash[:notice] = (@band.save) ? "Band added" : "Failure"
    redirect_to :back
  end

  def destroy
    @band = Band.find(params[:id])

    flash[:notice] = (@band.destroy) ? "Band removed" : "Failure"
    redirect_to bands_url
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def show
    @note  = Note.find(params[:id])
    @track = @note.track
    @album = @note.album
    @band  = @note.band
    @user  = @note.user
  end

  def create
    @note = Note.new(params[:note])

    flash[:notice] = (@note.save) ? "Note added" : "Failure"
    redirect_to :back
  end

  def destroy
    @note = Note.find(params[:id])
    @track = @note.track

    flash[:notice] = (@note.destroy) ? "Track removed" : "Failure"
    redirect_to track_url(@track.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],
                                     params[:user][:password])

    if @user
      login(@user)
      flash[:notice] = "Logged in"
      redirect_to user_url(@user)
    else
      flash[:notice] = "Failure"
      redirect_to login_page_url
    end
  end

  def destroy
    logout
    flash[:notice] = "Logged out"
    redirect_to root_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show
    @track = Track.find(params[:id])
    @album = @track.album
    @band  = @track.band
    @notes = @track.notes
  end

  def create
    @track = Track.new(params[:track])

    flash[:notice] = (@track.save) ? "Track added" : "Failure"
    redirect_to :back
  end

  def destroy
    @track = Track.find(params[:id])
    @album = @track.album

    flash[:notice] = (@track.destroy) ? "Track removed" : "Failure"
    redirect_to album_url(@album.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if UserMailer.welcome_email(@user).deliver
      flash[:notice] = "Mail sent"
      redirect_to root_url
    else
      flash[:notice] = "Failure"
    redirect_to root_url
    end
  end

  def show
    redirect_to root_url if current_user.id != params[:id].to_i
    @user = current_user
    @notes = @user.notes
  end

  def activate

  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def login(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to root_url unless current_user
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_album.html.erb
<%= link_to album.album_name, album_url(album) %>
<% if params[:controller] == "albums" && params[:action] == "show" %>
  <%= button_to "Delete", album_url(album), method: "delete" %>
<% end %>
<br>

app/views/albums/_form.html.erb
<form action="<%= albums_url %>" method="post">
  <input type="hidden"
         name="album[band_id]"
         value="<%= @band.id %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="album_name">Album Name: </label>
  <input type="text" name="album[album_name]" id="album_name"><br>

  <input type="submit" value="Create">
</form>

app/views/albums/show.html.erb
<h2><%= @band.band_name %> > <%= @album.album_name %></h2>

<%= button_to "Delete #{@album.album_name}",
    album_url(@album),
    method: "delete" %>

<br>
Tracks (<%= @tracks.count %>):<br>
<%= render @tracks %>

<br><hr><br>

<strong>Add New Track</strong><br><br>
<%= render 'tracks/form' %>

<br><hr><br>

<%= link_to "Band's Albums", band_url(@album.band_id) %>

app/views/bands/_band.html.erb
<%= link_to band.band_name, band_url(band) %>
<% if params[:controller] == "bands" && params[:action] == "show" %>
  <%= button_to "Delete", band_url(band), method: "delete" %>
<% end %>
<br>

app/views/bands/_form.html.erb
<form action="<%= bands_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="band_name">Band's Name: </label>
  <input type="text" name="band[band_name]" id="band_name"><br>

  <input type="submit" value="Create">
</form>

app/views/bands/index.html.erb
<h2>Band List</h2>

<%= render @bands %>

<br><hr><br>

<strong>Add New Band</strong><br><br>
<%= render 'form' %>

app/views/bands/show.html.erb
<h2><%= @band.band_name %></h2>

<%= button_to "Delete #{@band.band_name}",
    band_url(@band),
    method: "delete" %>
<br><hr><br>
Albums (<%= @albums.count %>):<br>

<%= render @albums %>

<br><hr><br>

<strong>Add New Album</strong><br><br>
<%= render 'albums/form' %>

<br><hr><br>

<%= link_to "All Bands", bands_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless flash[:notice].nil? %>
  <%= flash[:notice] %>
  <br><hr><br>
<% end %>
<br>

<table>
  <tr>
  <td>
    <%= link_to "Home", root_url %>
  </td>
  </tr>
  <tr>
<% if current_user.nil? %>
  <td>
    <%= link_to "Login Here", login_page_url %>
  </td>
  </tr>
  <tr>
  <td>
    <%= link_to "Register", new_user_url %>
  </td>
<% else %>
  <td>
    Logged in as <%= link_to current_user.username, user_url(current_user)%>
  </td>
  <td>
    <%= button_to "Logout", logout_url, method: "delete" %>
  </td>
<% end %>
  </tr>
</table>

<br><br><hr><br>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<form action="<%= notes_url %>" method="post">
  <input type="hidden"
         name="note[track_id]"
         value="<%= @track.id %>">

  <input type="hidden"
         name="note[user_id]"
         value="<%= current_user.id %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="note_text">Note: </label>
  <input type="text" name="note[text]" id="note_text"><br>

  <input type="submit" value="Create">
</form>

app/views/notes/_note.html.erb
<%= User.find(note.user_id).username %>: <%= note.text %>

<% if current_user && current_user.id == note.user_id %>
  <%= link_to "Delete", note_url(note), method: "delete" %>
<% end %>

<br>

app/views/tracks/_form.html.erb
<form action="<%= tracks_url %>" method="post">
  <input type="hidden"
         name="track[album_id]"
         value="<%= @album.id %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="track_name">Track Name: </label>
  <input type="text" name="track[track_name]" id="track_name"><br>

  <input type="submit" value="Create">
</form>

app/views/tracks/_track.html.erb
<%= link_to track.track_name, track_url(track) %>
<% if params[:controller] == "tracks" && params[:action] == "show" %>
  <%= button_to "Delete", track_url(track), method: "delete" %>
<% end %>
<br>

app/views/tracks/show.html.erb
<h2><%= @band.band_name %> >
    <%= @album.album_name %> >
    <%= @track.track_name %></h2>

<%= button_to "Delete #{@track.track_name}",
    track_url(@track),
    method: "delete" %>

<br>
Notes (<%= @notes.count %>):<br><br>
<%= render @notes %>

<br><hr><br>

<% if current_user %>
  <strong>Add New Note</strong><br><br>
  <%= render 'notes/form' %>
  <br><hr><br>
<% end %>

<%= link_to "Album Tracks", album_url(@track.album_id) %>

app/views/users/new.html.erb
<h2>Create New User</h2>
<br>

<form action="<%= users_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="username">Username: </label>
  <input type="text" name="user[username]" id="username"><br>

  <label for="email">Email: </label>
  <input type="text" name="user[email]" id="email"><br>

  <label for="password">Password: </label>
  <input type="password" name="user[password]" id="password"><br>

  <input type="submit" value="Create">
</form>

<p><%= link_to "All Users", users_url %></p>

app/views/users/show.html.erb
<h2>User's Profile</h2>
<br>
Username: <%= @user.username %><br>
Email:    <%= @user.email %><br><br>

Your notes:<br>
<% @notes.each do |note| %>
  <%= link_to Track.find(note.track_id).track_name, track_url(note.track_id) %>: "<%= note.text %>" <br>
<% end %>
<br>